---
- name: Collect the host informations
  hosts: web
  max_fail_percentage: 30% 
  serial: 
     - 1
     - 10 
     - 100% 
  tasks:
   - name: Call the template 
     template:
      src: hosts.j2 
      dest: /home/student/hosts
     delegate_to: localhost 
     become: true
   - debug:
      msg: task 2 will run
