---
- name: Generate password
  hosts: server1 
  tasks:
   - name: Generate a Random password in 10 digits
     debug:
      msg: "{{ password }}"
     vars:
      password: "{{ query('password', '/home/student/mypass chars=ascii_lowercase, length=5')}}"
